export const units = [
  "g/cm3",
  "g/L",
  "kg/m3",
  "kg/L",
  "kPa/m",
  "SG",
  "m3/sk",
  "lb/ft3",
  "lb/bbl",
  "psi/ft",
  "psi/100ft",
  "SG",
  "ppg",
];
export const itemOfMenuInitial = [
  {
    id: 0,
    title: "Drilling conversions",
    sons: [
      "Mud Weight units",
      "Axial Spring Constant",
      "Axial Dampening Coef",
      "Torsional Spring Constant",
      "Pressure Gradient units",
      "Yield Slurry units",
      "Footage Cost units",
      "Dogleg units",
      "Float Rate units",
      "Drilling Rate units",
      "Weight length units",
      "Geothermal Gradient",
    ],
  },
  { id: 1, title: "Production conversions" },
  { id: 2, title: "Force and Power  conversions" },
  { id: 3, title: "Fluid conversions" },
  { id: 4, title: "Gas conversions" },
  { id: 5, title: "General conversions" },
];
